import { ArrowRight, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import EmptyState from '../components/EmptyState'
import PageIntro from '../components/PageIntro'
import { useStore } from '../context/StoreContext'
import { formatCurrency } from '../utils/format'

export default function Cart() {
  const { cart, subtotal, updateQuantity, removeFromCart, clearCart } = useStore()
  const shipping = subtotal >= 100 ? 0 : 9
  return <><PageIntro eyebrow="Your considered collection" title="Shopping bag." />{cart.length ? <section className="container cart-layout"><div className="cart-list"><div className="cart-list-head"><span>{cart.length} {cart.length === 1 ? 'item' : 'items'}</span><button onClick={clearCart}>Clear bag</button></div>{cart.map((item) => <article className="cart-item" key={item.id}><Link to={`/products/${item.id}`}><img src={item.image} alt={item.name} /></Link><div className="cart-item-info"><span>{item.category}</span><Link to={`/products/${item.id}`}><h2>{item.name}</h2></Link><small>{item.color}</small><div className="quantity compact"><button onClick={() => item.quantity === 1 ? removeFromCart(item.id) : updateQuantity(item.id, item.quantity - 1)} aria-label="Decrease"><Minus /></button><span>{item.quantity}</span><button onClick={() => updateQuantity(item.id, item.quantity + 1)} aria-label="Increase"><Plus /></button></div></div><strong>{formatCurrency(item.price * item.quantity)}</strong><button className="remove-item" onClick={() => removeFromCart(item.id)} aria-label={`Remove ${item.name}`}><Trash2 /></button></article>)}</div><aside className="order-card"><span className="eyebrow">Order summary</span><h2>Your total</h2><div><span>Subtotal</span><strong>{formatCurrency(subtotal)}</strong></div><div><span>Delivery</span><strong>{shipping ? formatCurrency(shipping) : 'Complimentary'}</strong></div><div className="total"><span>Total</span><strong>{formatCurrency(subtotal + shipping)}</strong></div><p>Taxes calculated at checkout.</p>{shipping > 0 && <div className="shipping-progress"><span>Add {formatCurrency(100 - subtotal)} for free delivery</span><div><i style={{ width: `${Math.min(subtotal, 100)}%` }} /></div></div>}<Link className="button dark checkout-button" to="/checkout">Continue to checkout <ArrowRight size={17} /></Link><Link className="text-link continue" to="/shop">Continue shopping</Link></aside></section> : <section className="container account-page"><EmptyState icon={<ShoppingBag />} title="Your bag is feeling light" text="Explore our collection of objects made to be used, loved, and kept." /></section>}</>
}
